name: Collect And Verify Proxy Servers

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1,13 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run SubConverter
        run: |
          wget https://github.com/tindy2013/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz
          tar -zxvf subconverter_linux64.tar.gz
          cd subconverter/
          nohup ./subconverter &
      - name: Install dependencies
        run: |
          sudo timedatectl set-timezone 'Asia/Shanghai'
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mkdir /tmp/download
          cd /tmp/download
          wget https://github.com/Dreamacro/clash/releases/download/v1.11.12/clash-linux-amd64-v3-v1.11.12.gz
          gzip -d clash-linux-amd64-v3-v1.11.12.gz
          sudo mv clash-linux-amd64-v3-v1.11.12 /usr/bin/clash
          sudo chmod +x /usr/bin/clash
          clash -t
      - name: Run Python Scripts
        run: |
          python collectproxy.py
      - name: Upload Result
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: output
          folder: output
